### ISSUE TITLE
Find at least two datasets

### ISSUE THREAD

**Issue by escapa12** [AgileDataScienceUB/ADS4#1]
In order to be able to train a model, we need to find a dataset. Since our product has to be robust and able to work in different contexts, we want to find at least two different datasets.

**Estimated time**: 0.5 hours

**Comment by riccardobucco** [comment]
The first dataset that we found is the IBM one: [https://www.ibm.com/communities/analytics/watson-analytics-blog/hr-employee-attrition/](url)

**Comment by riccardobucco** [comment]
You can find the second dataset on kaggle: [https://www.kaggle.com/HRAnalyticRepository/employee-attrition-data](url)
