### ISSUE TITLE
Find 2 more datasets

### ISSUE THREAD

**Issue by lucas-lr** [AgileDataScienceUB/ADS4#15]
Find 2 more datasets in order to simulate our company has 3 different clients and check that our system works for different datasets.

Effort: 2

**Comment by escapa12** [comment]
I found these datasets:

https://www.kaggle.com/HRAnalyticRepository/employee-attrition-data
https://www.ibm.com/communities/analytics/watson-analytics-blog/hr-employee-attrition/
https://www.kaggle.com/analystanand/employee-attrition
