### ISSUE TITLE
Selection of the best features

### ISSUE THREAD

**Issue by lucas-lr** [AgileDataScienceUB/ADS4#16]
We have to select the best features from the datasets. Indeed, some of them are more useful than others, so we should focus on them, ignoring the others.

**Estimated time**: 8 hours

**Comment by escapa12** [comment]
We select a  commun amount of features that we will  request to our clients. Our algorithm will enreach them automatically taking in account their meaning. Extra  features may be also  included but the algorithm won't take advantatge of the domain when cleaning and enriching them. 

Descripcion of commun features on the wiki:
https://github.com/AgileDataScienceUB/ADS4/wiki/Data-consolidation
