### ISSUE TITLE
Create a feature selection algorithm

### ISSUE THREAD

**Issue by lucas-lr** [AgileDataScienceUB/ADS4#17]
Effort: 8

**Comment by escapa12** [comment]
The functions are implemented on the library studd.py Link: https://github.com/AgileDataScienceUB/ADS4/blob/analysis/data_analysis/stuff.py`

The notebook `performance.ipynb` is a demo of the algorithm:
Link:https://github.com/AgileDataScienceUB/ADS4/blob/analysis/data_analysis/lucas/performance.ipynb
