### ISSUE TITLE
Feature transformation algorithm for the different types of features (string / float).

### ISSUE THREAD

**Issue by lucas-lr** [AgileDataScienceUB/ADS4#18]
Methods for categorical features:
- One hot encoding
- Weight of evidence
- Clustering
- Etc.

Methods for continuous features:
- Outlier treatment
- Missing imputation
- Logarithm
- Etc.

**Estimated time**: 8

**Comment by escapa12** [comment]
The functions are implemented on the library ` studd.py` Link: https://github.com/AgileDataScienceUB/ADS4/blob/analysis/data_analysis/stuff.py`

**Comment by escapa12** [comment]
The notebook `performance.ipynb` is a demo of the algorithm:
Link:https://github.com/AgileDataScienceUB/ADS4/blob/analysis/data_analysis/lucas/performance.ipynb
