### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by riccardobucco** [AgileDataScienceUB/ADS4#26]
We have to check if the dataset contains some rows with missing data. Then, we have to discuss how to deal with them and, at the end, we have to write a document that describes which are our decisions about this problem.

**Estimated time**: 4

**Comment by riccardobucco** [comment]
We haven't found any missing value in the dataset!

**Comment by escapa12** [comment]
In the wiki we explain how we dealt with missing data.
Link: https://github.com/AgileDataScienceUB/ADS4/wiki/Data-cleaning
 The strategy is implemented in the file `pandoras_box.py`.
