### ISSUE TITLE
Deal with outliers

### ISSUE THREAD

**Issue by riccardobucco** [AgileDataScienceUB/ADS4#27]
We have to check if the dataset contains outliers. If we find out some outliers then we have to discuss how to deal with them. At the end of this activity, we should write a document that describes how we deal with those values.

**Estimated time**: 8

**Comment by riccardobucco** [comment]
We didn't find any incorrect value in the two datasets.

**Comment by escapa12** [comment]
Link wiki outliers: https://github.com/AgileDataScienceUB/ADS4/wiki/Data-cleaning
