### ISSUE TITLE
Integration of the datasets

### ISSUE THREAD

**Issue by riccardobucco** [AgileDataScienceUB/ADS4#28]
Since we want to work with many datasets, it's possible that they don't have the same structure. Indeed, they can be from many different sources and, for example, they can have different attributes. Thus, we have to find a way to deal with this problem: at the end, we want to have a coherent dataset to work with

**Estimated time**: 4 hours

**Comment by riccardobucco** [comment]
We have two datasets. One of them has one row for each employee, while the other one has many rows for each employee (one per year). We have decided to keep only one row for employee, aggregating the other info that we have

**Comment by escapa12** [comment]
The functions in  orhter to accomplish the task are implemented on the library `studd.py`
 Link: https://github.com/AgileDataScienceUB/ADS4/blob/analysis/data_analysis/stuff.py`
