### ISSUE TITLE
Technologies, programming languages and tools

### ISSUE THREAD

**Issue by escapa12** [AgileDataScienceUB/ADS4#5]

**Comment by acompanys** [comment]
Before starting the analysis activity, the team should agree on which are the technologies, the programming languages and the tools that we will use.

**Estimated time**: 1 hour

**Comment by riccardobucco** [comment]
For the analysis part (and for the backend itself) we chose to use Python.
For the webserver we chose to use Python, using the framework Flack
For the frontend we used HTML5/CSS3/Javascript

To make our job easier, we're also using Docker
