### ISSUE TITLE
Description of the features of the dataset

### ISSUE THREAD

**Issue by escapa12** [AgileDataScienceUB/ADS4#6]
The first thing to do when we have some datasets is to study their features, to have a general idea about the domain we are working with. It's important to write down a document containing the knowledge that we acquire in this step, since we don't want to have problems in the future caused by misunderstandings related to the features.

**Estimated time**: 1 hour

**Comment by riccardobucco** [comment]
We wrote down a description of the features we kept in the wiki!

**Comment by escapa12** [comment]
Link: https://github.com/AgileDataScienceUB/ADS4/wiki/Data-consolidation
